# Generated by Django 4.2 on 2024-10-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India')], help_text='Your current country.', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
