# Generated by Django 4.2 on 2024-10-03 10:35

import applicant.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(help_text='Upload your resume in PDF or Word format.', upload_to='resumes/%Y/%m/%d/', validators=[applicant.models.validate_file_size], verbose_name='Resume')),
                ('bio', models.TextField(blank=True, help_text='A brief summary about yourself and your career (max 500 characters).', null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Bio')),
                ('current_job_title', models.CharField(blank=True, help_text='Your current job title.', max_length=100, null=True, verbose_name='Current Job Title')),
                ('linkedin_profile', models.URLField(blank=True, help_text='Link to your LinkedIn profile.', null=True, verbose_name='LinkedIn Profile')),
                ('github_profile', models.URLField(blank=True, help_text='Link to your GitHub profile.', null=True, verbose_name='GitHub Profile')),
                ('portfolio_website', models.URLField(blank=True, help_text='Link to your portfolio website.', null=True, verbose_name='Portfolio Website')),
                ('experience_level', models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level'), ('Management Level', 'Management Level'), ('Executive Level', 'Executive Level')], help_text='Select your overall experience level.', max_length=50, null=True, verbose_name='Experience Level')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Enter the total years of professional experience.', null=True, verbose_name='Years of Experience')),
                ('highest_education', models.CharField(blank=True, choices=[('High School', 'High School'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate')], help_text='Select your highest level of education.', max_length=100, null=True, verbose_name='Your Highest Education')),
                ('city', models.CharField(blank=True, help_text='Your current city.', max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text='Your current state.', max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, help_text='Your current country.', max_length=100, null=True, verbose_name='Country')),
                ('is_available_for_work', models.BooleanField(default=True, help_text='Are you currently looking for work?', verbose_name='Available for Work')),
                ('willing_to_relocate', models.BooleanField(default=False, help_text='Are you willing to relocate for a job?', verbose_name='Willing to Relocate')),
                ('desired_salary', models.CharField(blank=True, help_text='Expected salary (e.g., $60,000 per year).', max_length=50, null=True, verbose_name='Desired Salary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
            },
        ),
    ]
