# Generated by Django 4.2 on 2024-10-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select the skills you possess.', related_name='applicants', to='job.skill', verbose_name='Skills'),
        ),
    ]
