# Generated by Django 4.2 on 2024-10-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='state',
        ),
    ]
